apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo
  namespace: default
  labels:
    app: todo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
  template:
    metadata:
      labels:
        app: todo
        azure.workload.identity/use: "true"
    spec:
      serviceAccountName: todo
      containers:
        - name: todo
          image: ${REGISTRY_NAME}.azurecr.io/todo-app:${IMAGE_TAG}
          ports:
            - containerPort: 8080
          env:
            - name: "ASPNETCORE_ENVIRONMENT"
              value: "Development"
          resources: {}
