apiVersion: v1
kind: Service
metadata:
  name: todo
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: todo
---
apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: "65fb8741-db03-4e22-9601-30a6c514b866"
  name: "todo"